### ISSUE TITLE
UI text changes to ellipsis when pressing Enter after changing increase/decrease amount on supply item

### ISSUE THREAD

**Issue by dreammac3816547290** [AY2223S1-CS2103T-W08-4/tp#161]
Bug Screenshot:
![10bf6f5b-b4aa-4d05-8a87-d1a52e0e4258](https://user-images.githubusercontent.com/95905466/197911507-7380eb0b-e0af-4206-b168-fd45cd7d594c.jpg)
Json File:
![image](https://user-images.githubusercontent.com/95905466/197911444-06fe5956-b34b-434d-98e9-4cc174dbf9d9.png)

**Comment by hauchongtang** [comment]
Noted.

**Comment by hauchongtang** [comment]
# Steps to replicate
1. Launch `Main.main()`
2. Immediately click on `TextField` and hit `Enter`.
3. **Visual bug** shows as seen in the screenshot above.

# Possible solutions
1. Remove `onAction` event handler from this node.
2. Enable both `onAction` and `onMouseMoved`

# Taken solution
* Solution 2
