### ISSUE TITLE
[PE-D][Tester D] Bug: Minimum stock not displayed for inventory items

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#177]
![Screenshot 2022-10-28 at 4.18.22 PM.png](https://raw.githubusercontent.com/jeromepui/ped/main/files/40351c31-2990-4d2a-b4d5-5e05391ca0ef.png)

Providing a label that shows the minimum stock for each inventory item would be useful for the user to calculate how much more items they need to stock up on.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jeromepui/ped#1

**Comment by weesiau** [comment]
Should we show minimum stock also, or is this intended behaviour?

**Comment by hauchongtang** [comment]
intended
