### ISSUE TITLE
[PE-D][Tester D] Bug: editStock command does not allow a number longer than 10 digits to be entered

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-4/tp#186]
Steps to reproduce:
1. Enter `editStock INDEX c/12345678912` in the command box. INDEX can be refer to any item in the list.

Expected: Item count should be updated.

Actual: Error message shown: "You did not provide a value to c/."

![Screenshot 2022-10-28 at 4.27.13 PM.png](https://raw.githubusercontent.com/jeromepui/ped/main/files/cf5b944e-7134-4b1b-9749-a12aeb34b018.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jeromepui/ped#2

**Comment by Bahamas20** [comment]
It should not allow because editStock takes integers and max value for integer is like 2,000,000,000. Added in user guide that editStock should not allow more than 9digits
