### ISSUE TITLE
[PE-D][Tester B] Wrong error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-4/tp#188]
![Screenshot 2022-10-28 at 4.28.49 PM.png](https://raw.githubusercontent.com/adeearyaa/ped/main/files/ba812ccd-20f9-456b-9316-ef57e6cc6a9a.png)
Wrong error message here it should say that this supplier already exists, also point to improve why cant I have one supplier supplying more than one types of food. Quite sure this is the norm in the real world

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: adeearyaa/ped#5

**Comment by hauchongtang** [comment]
Intended right ? @Bahamas20

**Comment by Bahamas20** [comment]
Second part is intended will specify in user guide

**Comment by Bahamas20** [comment]
The command input is also invalid, no space between ABC Pte Ltd and p/
