### ISSUE TITLE
[PE-D][Tester E] Lack of visuals and explanations for list commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#189]
When entered into the command box, the "listSuppliers", "listTasks", "listInventory" commands do not seem to perform any function as the UI remains unchanged after performing the commands. There are also a lack of visuals provided in the UG to illustrate what these commands actually do, which makes it confusing for the user to understand the actual function of these commands. 

-------------
Labels: `type.DocumentationBug` `severity.High`
original: rycs2812/ped#4

**Comment by hauchongtang** [comment]
Not sure why is it a severity high but I guess we can explain that it is to list all items etc in the UG.
