### ISSUE TITLE
[PE-D][Tester C] Problem when adding a supplier

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#194]
![Screenshot 2022-10-28 at 4.35.27 PM.png](https://raw.githubusercontent.com/bryanhce/ped/main/files/1a22063e-1694-4092-9c0f-0a630ffd2a13.png)

When I typed in the exact command that was suggested as an example from the error message in the result display bar, the error returned was invalid command format. This could be because there is a missing space between the name and the p prefix.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: bryanhce/ped#6

**Comment by weesiau** [comment]
This is due to a small typo in the example command, will fix

**Comment by Bahamas20** [comment]
This is already fixed by fixing #176
