### ISSUE TITLE
[PE-D][Tester D] Bug: Edit command allows phone number to be more than 8 digits

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#206]
Steps to reproduce:
1. Enter `edit INDEX p/99999999999999`
2. Press 'Enter' to execute the command.

Expected: Error message should be shown, invalid phone numbers should not be allowed.

Actual: Phone number is edited.

![Screenshot 2022-10-28 at 4.47.10 PM.png](https://raw.githubusercontent.com/jeromepui/ped/main/files/b0bd0f54-10e0-467d-8279-d764288c60cf.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jeromepui/ped#5

**Comment by hauchongtang** [comment]
This one we got enforce from the addSupplier already isit ?
