### ISSUE TITLE
[PE-D][Tester D] Bug: Item field for add command should not take all values

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-4/tp#214]
![Screenshot 2022-10-28 at 4.56.58 PM.png](https://raw.githubusercontent.com/jeromepui/ped/main/files/10b63313-8ba6-4fc4-9a90-bf9fdfde5125.png)

Items should not include numbers in their names but this application seems to suggest that it is possible.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jeromepui/ped#8

**Comment by weesiau** [comment]
Items can have numbers in them. e.g. (00 Flour)
