### ISSUE TITLE
[PE-D][Tester A] Unable to insert more than 1 tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#227]
### Should insert more than 1 tag in case of multiple descriptions of the supplier

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Chustinjeng/ped#3

**Comment by hauchongtang** [comment]
Is this our intended behavior ?

**Comment by weesiau** [comment]
Multiple tags allowed, each tag must be only one word. UG will be updated to reflect this
