### ISSUE TITLE
[PE-D][Tester F] Size of Window 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-4/tp#230]
The app by default occupies the entire screen. Even when I try to minimise my app panel, *when I scroll to the most bottom*, several cards for the Suppliers and  Inventory cannot be reached. 

![Screenshot 2022-10-28 at 5.42.39 PM.png](https://raw.githubusercontent.com/sltsheryl/ped/main/files/2ae4f825-f452-4334-92f1-40964142e7ac.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: sltsheryl/ped#11

**Comment by hauchongtang** [comment]
Hmm ok will look into this..

**Comment by hauchongtang** [comment]
@weesiau @Bahamas20 Yall got this problem ?

**Comment by weesiau** [comment]
Just tested with our release version.

Upon first startup:
<img width="1438" alt="Screenshot 2022-10-30 at 19 21 43" src="https://user-images.githubusercontent.com/25026164/198875861-24970af8-689b-4ab3-8f38-5f34c51eb9da.png">

After resizing (double clicking title bar to auto resize):
<img width="1438" alt="Screenshot 2022-10-30 at 19 22 38" src="https://user-images.githubusercontent.com/25026164/198875885-e6224a70-04a9-4940-82d8-f10ee806dd4c.png">

Am able to scroll to the bottom of the lists

**Comment by hauchongtang** [comment]
Ok then it might affect operation of the whole app

**Comment by hauchongtang** [comment]
so i set a default startup width and height.
