### ISSUE TITLE
[PE-D][Tester A] Faulty table of contents in UG 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-4/tp#242]
![Screenshot 2022-10-28 at 11.29.36 PM.png](https://raw.githubusercontent.com/Chustinjeng/ped/main/files/e154b5a5-e1de-4ccf-bd46-b7731aa3e5d0.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Chustinjeng/ped#15

**Comment by weesiau** [comment]
The ToC is working on the hosted site 
https://ay2223s1-cs2103t-w08-4.github.io/tp/UserGuide.html
